[features]
seeds = false
skip-lint = false
[programs.localnet]
launchpad = "8fBCPWGdwm4ThwKUZtELsL9EW9mqyQLzBNFDW2iJkhst"
[programs.devnet]
launchpad = "8fBCPWGdwm4ThwKUZtELsL9EW9mqyQLzBNFDW2iJkhst"
[programs.mainnet]
launchpad = "8fBCPWGdwm4ThwKUZtELsL9EW9mqyQLzBNFDW2iJkhst"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/bear/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
